# Generated by Django 3.2.21 on 2023-09-25 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_alter_review_image'),
        ('best_deals', '0002_alter_bestdeals_image'),
        ('comments', '0002_remove_comment_deal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='ReviewComment',
        ),
        migrations.CreateModel(
            name='DealsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='best_deals.bestdeals')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
