# Generated by Django 3.2.21 on 2023-12-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20230925_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealsComment',
        ),
    ]
