# Generated by Django 3.2.21 on 2023-12-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealLike',
        ),
    ]
