# Generated by Django 3.2.21 on 2023-09-21 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('stars', models.CharField(choices=[('1', 1), ('1.5', 1.5), ('2', 2), ('2.5', 2.5), ('3', 3), ('3.5', 3.5), ('4', 4), ('4.5', 4.5), ('5', 5)], max_length=3)),
                ('genre', models.CharField(choices=[('Sandbox', 'Sandbox'), ('Real-time strategy', 'Real-time strategy'), ('Shooters', 'Shooters'), ('Multiplayer online battle arena', 'Multiplayer online battle arena'), ('Role-playing', 'Role-playing'), ('Simulation and sports', 'Simulation and sports'), ('Action adventure', 'Action adventure'), ('Survival', 'Survival'), ('Horror', 'Horror')], max_length=100)),
                ('developed_by', models.CharField(max_length=255)),
                ('level_of_difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Extreme', 'Extreme'), ('Nightmare', 'Nightmare')], max_length=50)),
                ('suitable_age', models.CharField(choices=[('3', 3), ('7', 7), ('12', 12), ('16', 16), ('18', 18)], max_length=15)),
                ('hours_spent', models.IntegerField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, default='../default_post_g1aaa6.jpg', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
