# Generated by Django 3.2.21 on 2023-09-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hours_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
