# Generated by Django 3.2.21 on 2023-09-24 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Percentage discount', 'Percentage discount'), ('Pounds off', 'Pounds off'), ('Buy One Get One', 'Buy One Get One'), ('Multi-buy', 'Multi-buy'), ('Free shipping', 'Free shipping'), ('Try before you buy', 'Try before you buy'), ('Gift with purchase', 'Gift with purchase'), ('Other', 'Other')], max_length=100)),
                ('image', models.ImageField(blank=True, default='../default_post_g1aaa6.jpg', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
