# Generated by Django 3.2.21 on 2023-09-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestdeals',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
